#ifndef _LCOM_MENUS_H
#define _LCOM_MENUS_H

#include "../headers/mouse.h"
#include "../headers/sprite.h"

/**
 * @brief Game main state machine
 * 
 */
typedef enum
{
    MENU,
    RACE,
    RACE_WITH_FRIEND,
    BEST_RESULTS,
    RESULTS,
    EXIT
} Menu_state;

/**
 * @brief Possible events of keyboard and mouse typing or clicking in a button
 * 
 */
typedef enum
{
    click_on_race,
    click_on_race_with_friend,
    click_on_best_results,
    click_on_exit,
    click_on_results_exit,
    click_on_try_again_race,
    click_on_try_again_friends_race,
    click_on_best_results_back,
    type_ESC,
    type_down_arrow,
    type_top_arrow,
    type_right_arrow,
    type_left_arrow, 
    none 
} Menu_event;

/* "Race" option (x,y) positions */
#define race_x_left  27
#define race_x_right 173
#define race_y_top   268
#define race_y_down  328

/* "Race with friend" option (x,y) positions */
#define friend_race_x_left  303
#define friend_race_x_right 496
#define friend_race_y_top   448
#define friend_race_y_down  532

/* "Best results" option (x,y) positions */
#define best_results_x_left  309
#define best_results_x_right 488
#define best_results_y_top   63
#define best_results_y_down  141

/* "Exit" option (x,y) positions */
#define exit_x_left  625
#define exit_x_right 771
#define exit_y_top   267
#define exit_y_down  329

/* "Try again" option (x,y) positions */
#define try_again_x_left   250     
#define try_again_x_right  400     
#define try_again_y_top    420     
#define try_again_y_down   470      

/* "Exit" option (x,y) positions from results page*/
#define results_exit_x_left   450     //!x top-left position of "Exit" rectangle
#define results_exit_x_right  550     //!y right position of "Exit" rectangle 
#define results_exit_y_top    420     //!x top position of "Exit" rectangle
#define results_exit_y_down   470     //!y down position of "Exit" rectangle  

/* "Back" option (x,y) positions from best results page*/
#define best_results_back_x_left   685     //!x left position of "Back" rectangle 
#define best_results_back_x_right  785     //!y right position of "Back" rectangle 
#define best_results_back_y_top    520     //!x top position of "Back" rectangle
#define best_results_back_y_down   570     //!y down position of "Back" rectangle  

/**
 * @brief Process timer interrupt in menu page
 * @details Draw main menu and mouse 
 * @param counter Timer count 
 * @param main_menu Main menu sprite
 * @param mouse Mouse sprite
 */
void menus_process_timer_int(uint32_t counter, Sprite* main_menu, Sprite* mouse);
/**
 * @brief Process keyboard interrupt in menu page
 * @details Check if it is to go to another page and change state if so
 * @param state Current state of state machine
 * @param aux_key Key to process
 */
void menus_process_kbd_int(Menu_state *state, uint8_t aux_key);
/**
 * @brief Process mouse interrupt in menu page
 * @details Check if it is to go to another page and change state if so. Move mouse
 * @param state Current state of state machine
 * @param mouse_event Mouse event
 * @param mouse Mouse sprite
 */
void menus_process_mouse_int(Menu_state *state, Mouse_event mouse_event, Sprite* mouse);


/**
 * @brief Get Menu event generated by keyboard action
 * 
 * @param aux_key Key to process
 * @return Menu_event 
 */
Menu_event read_kbd_event(uint8_t aux_key);
/**
 * @brief Get Menu event generated by mouse action
 * 
 * @param ev Mouse event
 * @param mouse_x X position of mouse
 * @param mouse_y Y position of mouse
 * @return Menu_event 
 */
Menu_event read_mouse_event(Mouse_event *ev, int32_t *mouse_x, int32_t *mouse_y);

#endif /* _LCOM_MENUS_H */
